
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/proj-organic-f23-6pm-2
owner: ucsb-cs156-f23
repo_name: proj-organic-f23-6pm-2
pull_requests: [{"author":{"id":"MDQ6VXNlcjU5Mzc5NDY0","is_bot":false,"login":"justinchung712","name":""},"headRefName":"userManagement-backend-toggle","number":15,"title":"Create backend endpoints to toggle admin and instructor","url":"https://github.com/ucsb-cs156-f23/proj-organic-f23-6pm-2/pull/15"},{"author":{"id":"MDQ6VXNlcjI2Njk2NTky","is_bot":false,"login":"SparklyJeff","name":"Jeffrey Cao"},"headRefName":"jeffrey-fix-spacing-issue","number":14,"title":"fixed spacing issue in class","url":"https://github.com/ucsb-cs156-f23/proj-organic-f23-6pm-2/pull/14"}]
