
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/proj-organic-f23-6pm-2
owner: ucsb-cs156-f23
repo_name: proj-organic-f23-6pm-2
pull_requests: [{"author":{"id":"MDQ6VXNlcjY4NzUyNjY1","is_bot":false,"login":"ZhenyuYu1","name":"Zhenyu Yu"},"headRefName":"coursesEditPage2","number":70,"title":"[Course] F4: Courses Edit page with tests and storybook","url":"https://github.com/ucsb-cs156-f23/proj-organic-f23-6pm-2/pull/70"},{"author":{"id":"MDQ6VXNlcjU5Mzc5NDY0","is_bot":false,"login":"justinchung712","name":""},"headRefName":"coursesCreatePage","number":69,"title":"[Course] F3: Courses Create page with tests and stories","url":"https://github.com/ucsb-cs156-f23/proj-organic-f23-6pm-2/pull/69"},{"author":{"id":"MDQ6VXNlcjU5Mzc5NDY0","is_bot":false,"login":"justinchung712","name":""},"headRefName":"coursesIndexPage","number":68,"title":"[Course] F2: Courses Index page with tests and stories","url":"https://github.com/ucsb-cs156-f23/proj-organic-f23-6pm-2/pull/68"},{"author":{"id":"MDQ6VXNlcjY4NzUyNjY1","is_bot":false,"login":"ZhenyuYu1","name":"Zhenyu Yu"},"headRefName":"B3-schools-controller","number":67,"title":"[School] B3: Backend Issue: PUT, DELETE for Schools","url":"https://github.com/ucsb-cs156-f23/proj-organic-f23-6pm-2/pull/67"},{"author":{"id":"U_kgDOBdHvcw","is_bot":false,"login":"vedantshah99","name":"Vedant Shah"},"headRefName":"vedant-instructorCreateCourse","number":63,"title":"Instructor can create course","url":"https://github.com/ucsb-cs156-f23/proj-organic-f23-6pm-2/pull/63"}]
