
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/proj-organic-f23-6pm-2
owner: ucsb-cs156-f23
repo_name: proj-organic-f23-6pm-2
pull_requests: [{"author":{"id":"MDQ6VXNlcjU5Mzc5NDY0","is_bot":false,"login":"justinchung712","name":""},"headRefName":"coursesIndexPage","number":68,"title":"Courses index page with tests and stories","url":"https://github.com/ucsb-cs156-f23/proj-organic-f23-6pm-2/pull/68"},{"author":{"id":"MDQ6VXNlcjY4NzUyNjY1","is_bot":false,"login":"ZhenyuYu1","name":"Zhenyu Yu"},"headRefName":"B3-schools-controller","number":67,"title":"[School] B3: Backend Issue: PUT, DELETE for Schools","url":"https://github.com/ucsb-cs156-f23/proj-organic-f23-6pm-2/pull/67"},{"author":{"id":"MDQ6VXNlcjU5Mzc5NDY0","is_bot":false,"login":"justinchung712","name":""},"headRefName":"dateLabels","number":66,"title":"Fix courses api endpoints by fixing \"end\" postgres keyword conflict","url":"https://github.com/ucsb-cs156-f23/proj-organic-f23-6pm-2/pull/66"},{"author":{"id":"MDQ6VXNlcjg2NDkxMjg5","is_bot":false,"login":"cstraw2021","name":""},"headRefName":"chris-proftime","number":65,"title":"fix \"last online\" error in Profile Page","url":"https://github.com/ucsb-cs156-f23/proj-organic-f23-6pm-2/pull/65"},{"author":{"id":"U_kgDOBdHvcw","is_bot":false,"login":"vedantshah99","name":"Vedant Shah"},"headRefName":"vedant-instructorCreateCourse","number":63,"title":"Instructor can create course","url":"https://github.com/ucsb-cs156-f23/proj-organic-f23-6pm-2/pull/63"},{"author":{"id":"MDQ6VXNlcjY4NzUyNjY1","is_bot":false,"login":"ZhenyuYu1","name":"Zhenyu Yu"},"headRefName":"F4-coursesEditPage","number":55,"title":"[Course] F4: Courses Edit page with tests and storybook","url":"https://github.com/ucsb-cs156-f23/proj-organic-f23-6pm-2/pull/55"},{"author":{"id":"MDQ6VXNlcjcyODM5MjIz","is_bot":false,"login":"whuang602","name":"Will H."},"headRefName":"temp_test","number":53,"title":"Test PR","url":"https://github.com/ucsb-cs156-f23/proj-organic-f23-6pm-2/pull/53"},{"author":{"id":"MDQ6VXNlcjcyODM5MjIz","is_bot":false,"login":"whuang602","name":"Will H."},"headRefName":"ChangeWebIcon","number":50,"title":"Change web icon","url":"https://github.com/ucsb-cs156-f23/proj-organic-f23-6pm-2/pull/50"},{"author":{"id":"U_kgDOBdHvcw","is_bot":false,"login":"vedantshah99","name":"Vedant Shah"},"headRefName":"vedant-B1-courseController","number":16,"title":"Completed B1: Backend POST / GET operations, Course Controller","url":"https://github.com/ucsb-cs156-f23/proj-organic-f23-6pm-2/pull/16"}]
