
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/proj-organic-f23-6pm-2
owner: ucsb-cs156-f23
repo_name: proj-organic-f23-6pm-2
pull_requests: [{"author":{"id":"MDQ6VXNlcjg2NDkxMjg5","is_bot":false,"login":"cstraw2021","name":""},"headRefName":"f1dev","number":33,"title":"f1 draft, ignore","url":"https://github.com/ucsb-cs156-f23/proj-organic-f23-6pm-2/pull/33"},{"author":{"id":"MDQ6VXNlcjU5Mzc5NDY0","is_bot":false,"login":"justinchung712","name":""},"headRefName":"coursesFixturesFormTable","number":32,"title":"Priority F1: fixtures, form component, and table component for Courses","url":"https://github.com/ucsb-cs156-f23/proj-organic-f23-6pm-2/pull/32"},{"author":{"id":"MDQ6VXNlcjg2NDkxMjg5","is_bot":false,"login":"cstraw2021","name":""},"headRefName":"chris-f1","number":31,"title":"Add UserTable + Story and Tests (F1) ","url":"https://github.com/ucsb-cs156-f23/proj-organic-f23-6pm-2/pull/31"},{"author":{"id":"MDQ6VXNlcjI2Njk2NTky","is_bot":false,"login":"SparklyJeff","name":"Jeffrey Cao"},"headRefName":"jeffrey-f1","number":29,"title":"F1-Add Toggle Admin and Instructor Buttons to frontend","url":"https://github.com/ucsb-cs156-f23/proj-organic-f23-6pm-2/pull/29"},{"author":{"id":"MDQ6VXNlcjcyODM5MjIz","is_bot":false,"login":"whuang602","name":"Will H."},"headRefName":"backendpt2","number":17,"title":"Backend Endpoint Interceptors and Updater","url":"https://github.com/ucsb-cs156-f23/proj-organic-f23-6pm-2/pull/17"},{"author":{"id":"U_kgDOBdHvcw","is_bot":false,"login":"vedantshah99","name":"Vedant Shah"},"headRefName":"vedant-B1-courseController","number":16,"title":"Completed B1: Backend POST / GET operations, Course Controller","url":"https://github.com/ucsb-cs156-f23/proj-organic-f23-6pm-2/pull/16"}]
